# Create figures

This notebook reproduces the figures from Hernandez et al. 2015.

```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
```

## Functions

```{r}
import <- function(base_folder) {
  #' Import all `results.txt` files and the `times.txt` file from the
  #' sub-folders of the specified base folder.
  #' 
  #' @param base_folder string, path to experiment folder

  # Import time
  time <- readLines(file.path(base_folder, "time.txt"), warn=FALSE)

  # Get path to each scenario sub-folder within the base folder
  subfolders <- list.dirs(base_folder, recursive = FALSE, full.names = TRUE)

  # Initialise empty list
  result_list <- list()
  
  # Loop through the scenario sub-folders
  for (folder_path in subfolders) {
  
    # Extract the final folder name from the path
    folder_name <- basename(folder_path)
  
    # Save results.txt, and add the scenario 
    result_list[[folder_name]] <- read.delim(file.path(folder_path,
                                                       "results.txt"))
    result_list[[folder_name]]$scenario <- folder_name
  }

  # Combine into single dataframe
  results <- do.call(rbind, result_list)
  rownames(results) <- NULL
  
  # Add forms
  results$forms <- results$throughput*3.2

  # Return the results table and the time
  return(list(results = results, time = time))
}
```

```{r}
run_time <- function(time) {
  #' Print the run time in seconds and minutes
  #' 
  #' @param time string, time (e.g. "0:05:17.186109")

  # Convert the times to difftime objects
  time_adj <- (as.numeric(strptime(time, format="%H:%M:%OS")) - 
               as.numeric(strptime("0:00:00", format="%H:%M:%OS")))
  
  # Sum the times
  total_time <- sum(unlist(time_adj))

  # Find time in seconds, or minutes, or hours and minutes
  sec <- paste0(round(total_time), " sec")
  min <- paste0(round(total_time/60), " mins")
  hour_min <- paste0(floor(total_time / 3600), " hours ",
                     floor((total_time %% 3600) / 60), " mins")
  
  # Print result
  print(paste0(sec, ", or ", min, ", or ", hour_min))
}
```

```{r}
plot_scatter <- function(data, savepath, nrow=NULL){
  #' Creates scatter plot of staff members against throughput with size of dots
  #' indicating wait time, and plots for each pre-screening scenario
  #' 
  #' @param data dataframe with results from model run
  #' @param savepath string, path to save figure to
  #' @param nrow int, number of rows in plot, if NULL then will go with default

  fig <- ggplot(data=data) + 
    geom_point(aes(x=resources, y=forms, size=time), alpha=0.7) +
    #scale_x_continuous(limits=c(0, 150)) +
    scale_y_continuous(limits=c(0, 16000), breaks=seq(0, 16000, 3000)) +
    facet_wrap(~scenario, nrow=nrow) +
    labs(size="Waiting Time (minutes)") + xlab("Staff Members") + ylab("Throughput (forms per hour)") +
    theme(axis.title.y = element_text( face='bold')) + theme(axis.title.x = element_text( face='bold')) +
    theme_bw(18) +
    theme(legend.position="top")
  
  ggsave(savepath, width = 10 , height = 10)
}
```

## Import results

Import results for each experiment.

```{r}
exp1 <- import("../python_outputs/experiment1")
exp2 <- import("../python_outputs/experiment2")
exp3 <- import("../python_outputs/experiment3")
```

## Experiment 1

### Run time

```{r}
run_time(exp1$time)
```

### Figure 5

```{r}
plot_scatter(exp1$results, "../r_outputs/figure5.png")
```

### Figure 6

```{r}
values <- exp1$results %>%
  # Full labels
  rename("Line Manager" = greeter,
         "Screener" = screener,
         "Dispenser" = dispenser,
         "Med. Eval" = medic) %>%
  # Round throughput to nearest whole number
  mutate(throughput = round(throughput)) %>%
  # Order by throughput, and remove duplicate rows so just one remains
  arrange(throughput) %>%
  filter(!duplicated(throughput))
 
# Sort results by resources and forms (descending)
#values <- values[with(values, order(-resources,-forms)),]
values
```

```{r}
melted <- melt(values, id=c('resources','forms','time','scenario', 'throughput')) %>%
  mutate(prescreen = as.numeric(gsub('[^0-9.]', '', scenario)),
         forms = round(forms))

melted
```

Check filter on forms v.s. throughput.

```{r}
melted %>% filter(forms >= 11498, forms <= 11710) %>% arrange(forms)
melted %>% filter(throughput >= 11498, throughput <= 11710)
```

```{r}
fig6 <- ggplot(data=melted %>% filter(forms >= 11498, forms <= 11710)) +
  geom_bar(stat='identity',aes(x=variable, y=value, fill=prescreen)) +
  xlab("Staff Type") +
  ylab("Number of staff") +
  theme(axis.title.y = element_text( face='bold')) +
  theme(axis.title.x = element_text( face='bold')) +
  scale_fill_gradient2(low = "white", high = "#363737") +
  theme_bw(18) +
  facet_wrap(~round(forms)) +
  theme(axis.text.x=element_text(angle=90))

ggsave("../r_outputs/figure6.png", width = 10 , height = 10)

fig6
```

## Experiment 2

### Run time

```{r}
run_time(exp2$time)
```

### Figure 7

```{r}
plot_scatter(exp2$results, "../r_outputs/figure7.png")
```

## Experiment 3

### Run time

```{r}
# run_time(exp3$time)
```

### Figure 8

```{r}
plot_scatter(exp3$results, "../r_outputs/figure8.png", nrow=2)
```
