# Experiment 1

This notebook reproduces the figures from experiment 1: Figure 5 and 6.

```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
```

## Import results

```{r}
# Get path to each scenario sub-folder within the base folder
base_folder <- "../python_outputs/experiment1"
subfolders <- list.dirs(base_folder, recursive = FALSE, full.names = TRUE)
```

```{r}
# Initialise empty lists
result_list <- list()
times <- list()

# Loop through the scenario sub-folders
for (folder_path in subfolders) {

  # Extract the final folder name from the path
  folder_name <- basename(folder_path)

  # Save results.txt, and add the scenario 
  result_list[[folder_name]] <- read.delim(file.path(folder_path, "results.txt"))
  result_list[[folder_name]]$scenario <- folder_name
  
  # Save time.txt
  times[[folder_name]] <- readLines(file.path(folder_path, "time.txt"), warn=FALSE)
}
```

```{r}
# Combine into single dataframe
results <- do.call(rbind, result_list)
rownames(results) <- NULL

# Add forms
results$forms <- results$throughput*3.2

results
```

## Create Figure 5

Plot staff against throughput, faceted by pre-screened percentage.

```{r}
fig5 <- ggplot(data=results) + 
  geom_point(aes(x=resources, y=forms, size=time), alpha=0.7) +
  #scale_x_continuous(limits=c(0, 150)) +
  #scale_y_continuous(limits=c(0, 12000), breaks=seq(0, 12000, 3000)) +
  facet_wrap(~scenario) +
  labs(size="Waiting Time (minutes)") + xlab("Staff Members") + ylab("Throughput (forms per hour)") +
  theme(axis.title.y = element_text( face='bold')) + theme(axis.title.x = element_text( face='bold')) +
  theme_bw(18) +
  theme(legend.position="top")

ggsave("../r_outputs/figure5.png", width = 10 , height = 10)

fig5
```

## Create Figure 6

```{r}
values <- results %>%
  # Full labels
  rename("Line Manager" = greeter,
         "Screener" = screener,
         "Dispenser" = dispenser,
         "Med. Eval" = medic) %>%
  # Round throughput to nearest whole number
  mutate(throughput = round(throughput)) %>%
  # Order by throughput, and remove duplicate rows so just one remains
  arrange(throughput) %>%
  filter(!duplicated(throughput))
 
# Sort results by resources and forms (descending)
#values <- values[with(values, order(-resources,-forms)),]
values
```

```{r}
melted <- melt(values, id=c('resources','forms','time','scenario', 'throughput')) %>%
  mutate(prescreen = as.numeric(gsub('[^0-9.]', '', scenario)),
         forms = round(forms))

melted
```

Check filter on forms v.s. throughput.

```{r}
melted %>% filter(forms >= 11498, forms <= 11710) %>% arrange(forms)
melted %>% filter(throughput >= 11498, throughput <= 11710)
```
Too many to just include all, so just chose a subset of that...

```{r}
melted %>% filter(prescreen == 10 | prescreen == 50) %>% arrange(forms)
```

```{r}
fig6 <- ggplot(data=melted %>% filter(prescreen == 10 & forms > 6000)) +
  geom_bar(stat='identity',aes(x=variable, y=value, fill=prescreen)) +
  xlab("Staff Type") +
  ylab("Number of staff") +
  theme(axis.title.y = element_text( face='bold')) +
  theme(axis.title.x = element_text( face='bold')) +
  #scale_fill_gradient2(low = "white", high = "#363737") +
  theme_bw(18) +
  facet_wrap(~round(forms)) +
  theme(axis.text.x=element_text(angle=90))

ggsave("../r_outputs/figure6.png", width = 10 , height = 10)

fig6
```

## Show times for experiment 1

```{r}
# Convert the times to difftime objects
#times_converted <- lapply(times, function(x) {
#  as.numeric(strptime(x, format="%H:%M:%OS")) - as.numeric(strptime("0:00:00", format="%H:%M:%OS"))
#})

# Sum the times
#total_time <- sum(unlist(times_converted))
#print(paste0(round(total_time), " sec, ", round(total_time/60), " min"))
```