name: hernandez2015
channels:
  - defaults
  - conda-forge
dependencies:
  - inspyred=1.0
  - pip=19.3.1
  - pytest=4.6.2
  - python=2.7.12
  - pip:
    - matplotlib==1.3.1
    - networkx==1.8.1
    - numpy==1.8.0
    - scipy==0.13.2
    - simpy==2.3.1