---
title: "Day 1"
author: "Amy Heather"
date: "2024-09-20"
categories: [setup, read, scope]
bibliography: ../../../quarto_site/references.bib
---

::: {.callout-note}

X. Total time used: Xh Xm (X%)

:::

## Previously: Contacted the authors

Contacted Ivan Hernandez over LinkedIn, who kindly add an MIT license to the repository to enable reuse.

## 14.38-14.52: Set-up repository

* Created repository from template
* Set up environment
* Modified template files:
    * `README.md`
    * quarto site `index.qmd`
    * `CITATION.cff`
    * `_quarto.yml`
* Set up site on GitHub pages (`quarto publish gh-pages`)

## 14.57-14.58: Upload code to repository

The code is available at <https://github.com/ivihernandez/staff-allocation/tree/master>. It is licensed under an MIT license.

## 15.00-15.08: Upload journal article and artefacts

The published article with the journal "Computers & Industrial Engineering" at <https://www.sciencedirect.com/science/article/pii/S0360835215000728> does not appear to have the rights to share the full article or reuse images.

The abstract is shared at [ACM Digital Library](https://dl.acm.org/doi/10.1016/j.cie.2015.02.015) and the [Stevens Institute](https://researchwith.stevens.edu/en/publications/optimal-staffing-strategies-for-points-of-dispensing) but both link to the journal website, with neither containing a green open-access version.

## 15.10-15.34: Read the article and defined scope

Read the article and identified what I think the scope of the reproduction to be. Outlined this on the scope quarto page then forwarded to Tom for review.

## Timings

```{python}
import sys
sys.path.append('../')
from timings import calculate_times

# Minutes used prior to today
used_to_date = 0

# Times from today
times = [
    ('14.38', '14.52')]

calculate_times(used_to_date, times)
```